all:
  hosts:
    {% raw %}{{cookiecutter.django_project_name}}:
      ansible_connection: "ssh"
      ansible_user: "{{ deploy_user_username }}"
      ansible_become_pass: "{{ deploy_user_password }}"
      ansible_host: "YOUR.SERVER.IP"
      ansible_port: "22"{% endraw %}
